top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
