top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/aaa
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/aaa
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/aaa

include $(top_srcdir)/build/special.mk

