top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/server/mpm
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/server/mpm
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
