top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os/unix
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os/unix
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
