top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/experimental
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/experimental
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/experimental
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
