top_srcdir   = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
top_builddir = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22
srcdir       = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/echo
builddir     = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/echo
VPATH        = /home/pocha/rails/terminal-codelearn/stress-tests/apache2-2.2.22/modules/echo

include $(top_srcdir)/build/special.mk

